name: inventree
description: InvenTree stock management

version: 0.19.3+102

environment:
  sdk: ^3.8.1

dependencies:
  adaptive_theme: ^3.3.0                  # Theme management (e.g. dark mode)
  async: any
  audioplayers: ^6.1.0                    # Play audio files
  cached_network_image: ^3.3.1            # Download and cache remote images
  camera: ^0.11.1                         # Camera
  cupertino_icons: ^1.0.8
  currency_formatter: ^2.2.1              # Currency formatting
  custom_image_crop: ^0.1.1               # Crop selected images
  datetime_picker_formfield: ^2.0.1       # Date / time picker
  device_info_plus: ^11.4.0               # Information about the device
  dropdown_search: ^5.0.6                 # Dropdown autocomplete form fields
  file_picker: ^10.1.4                    # Select files from the device
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  flutter_markdown: ^0.6.19               # Rendering markdown
  flutter_overlay_loader: ^2.0.0          # Overlay screen support
  flutter_speed_dial: ^6.2.0              # Speed dial / FAB implementation
  flutter_tabler_icons: ^1.43.0
  http: ^1.4.0
  image_picker: ^1.1.2                    # Select or take photos
  infinite_scroll_pagination: ^4.0.0      # Let the server do all the work!
  intl: ^0.20.2
  mobile_scanner: ^7.0.1                  # Barcode scanning support
  one_context: ^4.0.0                     # Dialogs without requiring context
  open_filex: ^4.7.0                      # Open local files
  package_info_plus: ^8.1.1               # App information introspection
  path: ^1.9.0
  path_provider: ^2.1.5                   # Local file storage
  sembast: ^3.6.0                         # NoSQL data storage
  sentry_flutter: 8.14.2                   # Error reporting
  url_launcher: ^6.3.1                    # Open link in system browser
  wakelock_plus: ^1.3.2                   # Prevent device from sleeping

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  test: ^1.22.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/image/icon.png
    - assets/image/logo_transparent.png
    - assets/release_notes.md
    - assets/credits.md
    - assets/sounds/barcode_scan.mp3
    - assets/sounds/barcode_error.mp3
    - assets/sounds/server_error.mp3

sentry:
  upload_debug_symbols: true
  upload_source_maps: true